name: Build Executables

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nuitka PySide6 opencv-python numpy pillow openvino psutil
          pip install wmi pywin32
          pip install pygrabber


      - name: Build with Nuitka (Windows)
        run: |
          nuitka --standalone --enable-plugin=pyside6 --enable-plugin=multiprocessing --enable-plugin=numpy --enable-plugin=anti-bloat --enable-console --windows-uac-admin --windows-icon-from-ico=icon.ico --output-dir=dist --output-filename=FaceRollCall.exe --follow-imports --lto=yes --jobs=4 --python-flag=no_site --assume-yes-for-downloads main.py --include-data-file=icon.ico=icon.ico --include-package=psutil --include-data-file=arrow_right.png=arrow_right.png --include-data-dir=yolo26n-face_openvino_model=yolo26n-face_openvino_model

      - name: Compress build output
        run: |
          copy yolo26n-face_openvino_model/yolo26n-face.bin dist/main.dist/yolo26n-face_openvino_model/yolo26n-face.bin
          Compress-Archive -Path dist/main.dist/* -DestinationPath dist/FaceRollCall-Windows.zip

      - name: Upload artifact (for debugging)
        uses: actions/upload-artifact@v4
        with:
          name: FaceRollCall-Windows-debug
          path: dist/FaceRollCall-Windows.zip

      - name: Create GitHub Release
        if: success() && github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/FaceRollCall-Windows.zip
          tag_name: v1.0.${{ github.run_number }}
          name: Release v1.0.${{ github.run_number }}
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
